---
- hosts: "{{ HOSTS is defined | ternary(HOSTS, PREFIX|default('')+'*') }}"
  become: yes
  vars:
    env: Dev
    activation_key: undef
    sat_url: "{{ lookup('env', 'FOREMAN_SERVER') }}"
  roles:
    - rhsm_register
